//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LevelEditor.rc
//
#define IDC_MYICON                      2
#define IDI_SMALL                       3
#define IDI_LEVELEDITOR                 4
#define IDC_LEVELEDITOR                 5
#define IDD_CONTROLS                    6
#define IDD_CONVERT                     7
#define IDD_VIEW_TEXTURE                8
#define IDD_SELECT_TEXTURE              9
#define ID_FILE_NEW                     10
#define ID_FILE_OPEN                    11
#define ID_FILE_SAVE                    12
#define ID_FILE_SAVEAS                  13
#define ID_FILE_EXPORT3D                14
#define ID_FILE_EXPORT3D_TEX            15
#define ID_FILE_EXPORT3D_LM             16
#define ID_FILE_EXIT                    17
#define ID_TOOLS_CONV_TEX               18
#define ID_TOOLS_VIEW_TEX               19
#define ID_HELP_CONTROLS                20
#define IDS_MAP                         100
#define IDB_MAP_FIT                     101
#define IDB_MAP_CONTROLS                102
#define IDS_MAP_INFO1                   103
#define IDS_MAP_SELECTED_COORDS         104
#define IDS_MAP_SELECTED_COORDS_L       105
#define IDS_MAP_HOVER_COORDS            106
#define IDS_MAP_HOVER_COORDS_L          107
#define IDS_RES_LABEL                   118
#define IDS_RES_WALL_TEX_LABEL          119
#define IDS_RES_WALL_TEX                120
#define IDS_RES_FLAT_TEX_LABEL          121
#define IDS_RES_FLAT_TEX                122
#define IDS_RES_W_LIGHTMAPS_LABEL       123
#define IDS_RES_W_LIGHTMAPS             124
#define IDS_RES_TOTAL_LABEL             125
#define IDS_RES_TOTAL                   126
#define IDS_RES_F_LIGHTMAPS_LABEL       127
#define IDS_RES_F_LIGHTMAPS             128
#define IDB_RES_REFRESH                 129
#define IDS_TITLE_LABEL                 130
#define IDS_TITLE_EDIT_1                131
#define IDR_ACCELERATOR1                131
#define IDS_TITLE_EDIT_2                132
#define IDD_HELP_LIGHTMAPS              132
#define IDD_CONVERT_LIGHTMAP            133
#define IDS_LAYERS_GROUPBOX             140
#define IDS_LAYERS_LABEL1               141
#define IDC_LAYERS_COMBO                143
#define IDS_LIST_GROUPBOX               150
#define IDS_LIST_LABEL1                 151
#define IDL_LIST_LIST                   153
#define IDS_DC_TEXTURE                  200
#define IDB_DC_CONVERT_WALL             201
#define IDB_DC_CONVERT_FLAT             202
#define IDS_DC_TEXTURE_256              203
#define IDS_DC_TEXTURE_128              204
#define IDS_DC_TEXTURE_64               205
#define IDS_DC_TEXTURE_32               206
#define IDS_DC_TEXTURE_16               207
#define IDS_DC_TEXTURE_8                208
#define IDS_DC_TEXTURE_4                209
#define IDS_DC_INFO_1                   210
#define IDS_DC_INFO_2                   211
#define IDS_DC_INFO_3                   212
#define IDS_DC_INFO_4                   213
#define IDC_DC_SLIDER                   214
#define IDC_DC_INTENSITY                215
#define IDC_DC_FILE                     216
#define IDC_DC_MODE                     217
#define IDC_DC_TRESHOLD                 218
#define IDS_DC_TRESHOLD_LABEL           219
#define IDS_DC_SLIDER_LEFT              220
#define IDS_DC_SLIDER_RIGHT             221
#define IDS_DC_SLIDER_LABEL             222
#define IDC_DC_RAW_INFO                 223
#define IDC_DC_RAW_INFO_LABEL           224
#define IDC_DC_OUTPUT                   225
#define IDC_SELECT_TEXTURE_LIST         226
#define IDS_PROPERTIES_GROUPBOX         300
#define IDS_PROPERTIES_LABEL1           301
#define IDS_PROP_PLAYER_L1              302
#define IDB_PROP_PLAYER_RIGHT           303
#define IDB_PROP_PLAYER_UP              304
#define IDB_PROP_PLAYER_LEFT            305
#define IDB_PROP_PLAYER_DOWN            306
#define IDS_PROP_WALL_IMAGE_TOP         310
#define IDB_PROP_WALL_IMAGE_TOP_SELECT  311
#define IDS_PROP_WALL_IMAGE_TOP_LABEL   312
#define IDS_PROP_WALL_IMAGE_RIGHT       313
#define IDB_PROP_WALL_IMAGE_RIGHT_SELECT 314
#define IDS_PROP_WALL_IMAGE_RIGHT_LABEL 315
#define IDS_PROP_WALL_IMAGE_BOTTOM      316
#define IDB_PROP_WALL_IMAGE_BOTTOM_SELECT 317
#define IDS_PROP_WALL_IMAGE_BOTTOM_LABEL 318
#define IDS_PROP_WALL_IMAGE_LEFT        319
#define IDB_PROP_WALL_IMAGE_LEFT_SELECT 320
#define IDS_PROP_WALL_IMAGE_LEFT_LABEL  321
#define IDB_ADD_ADDTOMAP                322
#define IDB_DC_CONVERT_LIGHTMAP         1030
#define ID_TOOLS_LIGHTMAPS              32791
#define ID_HELP_LIGHTMAPS               32793
#define ID_TOOLS_CONV_LIGHTMAPS         32794
#define ID_TOOLS_CONV_LIGHTMAP          32795
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
